apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k4all-operator-cluster-role
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k4all-operator-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k4all-operator-cluster-role
subjects:
- kind: ServiceAccount
  name: k4all-operator-controller-manager
  namespace: k4all-operator-system 